name: mcMMOmc
main: org.mcmmo.mcmmomc.mcMMOmc
version: ${project.version}
author: NuclearW
description: mcMMO more channels adds a few new channels that function similar to mcMMO channels, and integrate with them properly.
